// <auto-generated />
using System;
using IST.Zeiterfassung.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IST.Zeiterfassung.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Bis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErfasstAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Typ")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Von")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.Feiertag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstArbeitsfrei")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feiertage");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.TimeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Ende")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErfasstAm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ErfasstFürUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ErfasstVonUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstMontage")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("Pausenzeit")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjektName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ZeitmodellUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ErfasstFürUserId");

                    b.HasIndex("ErfasstVonUserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZeitmodellUserId");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Aktiv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeiertagsRegion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.Zeitmodell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("GleitzeitMonatslimit")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GleitzeitkontoAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IstGleitzeit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SaldoÜbertragAktiv")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("WochenSollzeit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zeitmodelle");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.Absence", b =>
                {
                    b.HasOne("IST.Zeiterfassung.Domain.Entities.User", "User")
                        .WithMany("Absences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.TimeEntry", b =>
                {
                    b.HasOne("IST.Zeiterfassung.Domain.Entities.User", "Betroffener")
                        .WithMany()
                        .HasForeignKey("ErfasstFürUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IST.Zeiterfassung.Domain.Entities.User", "Erfasser")
                        .WithMany()
                        .HasForeignKey("ErfasstVonUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IST.Zeiterfassung.Domain.Entities.User", null)
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId");

                    b.HasOne("IST.Zeiterfassung.Domain.Entities.User", "ZeitmodellUser")
                        .WithMany()
                        .HasForeignKey("ZeitmodellUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Betroffener");

                    b.Navigation("Erfasser");

                    b.Navigation("ZeitmodellUser");
                });

            modelBuilder.Entity("IST.Zeiterfassung.Domain.Entities.User", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
